### ISSUE TITLE
ImportError: No module named c

### ISSUE THREAD

**Issue by pakholkav** [open-craft/custom-form-app#6]
Hello,

I was trying to install this app to my Open edX Hawthorn.2 release.
I was following the steps in README file, but when I run migrations, I got this error

edxapp@edx:~/custom-form-app$ python /edx/app/edxapp/edx-platform/manage.py lms syncdb --migrate --settings=aws
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/manage.py", line 118, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 19, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named c

Can you please help me to fix it?

**Comment by bradenmacdonald** [comment]
Hard to say as there could be many causes for that issue.

But most likely you have set `ADDL_INSTALLED_APPS` to a string, when it should be an array.

i.e. change

```
ADDL_INSTALLED_APPS = "custom_reg_form"
```
to
```
ADDL_INSTALLED_APPS = ["custom_reg_form"]
```

Also, we advise against running the Hawthorn version of edX. It is unsupported, and likely has security vulnerabilities.  There have been three newer releases since that time.

**Comment by pakholkav** [comment]
Thank you!
